Made ruff corrections

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -21,25 +21,35 @@ exec 1>&2
 
 RED='\033[0;31m'
 NC='\033[0m' # No Color
-errors=0
+format_err=0
+check_err=0
+err=0
 
 echo 'Running "ruff format --check"'
 ruff format --check
 
-if [ "$?" -eq "1" ]; then
-	echo "${RED}Run \"ruff format\" before committing${NC}"
-	errors=1
+if [ "$?" -eq 1 ]; then
+	format_err=1
+	err=1
 fi
 
 echo ""
 echo 'Running "ruff check"'
 ruff check
 
-if [ "$?" -eq "1" ]; then
-	echo "${RED}Make ruff changes before committing${NC}"
-	errors=1
+if [ "$?" -eq 1 ]; then
+	check_err=1
+	err=1
 fi
 
-if [ "$errors" -eq "1" ] ; then
+if [ "${format_err}" -eq 1 ] ; then
+	echo "${RED}Run \"ruff format\" before committing${NC}"
+fi
+
+if [ "${check_err}" -eq 1 ] ; then
+	echo "${RED}Correct ruff errors before committing${NC}"
+fi
+
+if [ "${err}" -eq 1 ] ; then
 	exit 1
 fi
